name: esmr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  # core data
  - numpy
  - pandas
  # download / parse pipeline
  - requests
  - beautifulsoup4
  - pyyaml
  # CLI
  - click
  # dashboard
  - panel
  - param
  - geoviews
  - holoviews
  - hvplot
  # dev tools
  - pytest
  - flake8
  - pip:
    - -e .